name: Daily Multi Commit

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate random commits
      run: |
        git config --global user.name 'AryamanBot'
        git config --global user.email 'itsaryaman23@gmail.com'

        COMMITS=$(( ( RANDOM % 15 ) + 1 ))  # 1 to 15 random commits

        for i in $(seq 1 $COMMITS); do
          echo "Commit $i on $(date)" >> activity.txt
          git add activity.txt
          git commit -m "chore: random commit $i"
        done

        git push
